print("Hello world!")
print("How are you today")
print("I like to type like this")
print("this is fun")
print("Yay!, printing")
print("I'd much rather you 'not'")
print('I "said" do not touch this')
print("I gave 'Tina' all my money")
print("I haven't have had Tunafish")
